service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: 'us-east-1'

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
